services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: sheethappens
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: sheethappens_server
    env_file:
      - .env
    expose:
      - "3000"
    depends_on:
      - db

  db:
    image: postgres:17.2
    restart: unless-stopped
    container_name: sheethappens_db
    env_file:
      - .env
    expose:
      - "5432"
